### ISSUE TITLE
Hipspecifyer conflicts with QuickCheck

### ISSUE THREAD

**Issue by Warbo** [moajohansson/IsaHipster#4]
I'm trying to build hipspecifyer with GHC 7.8.4 and 7.10.1, but both fail with the following error:

```
[1 of 2] Compiling HipSpecifyer.Prelude ( HipSpecifyer/Prelude.hs, dist/build/HipSpecifyer/Prelude.o )

HipSpecifyer/Prelude.hs:2:47:
    Ambiguous occurrence ‘genericCoarbitrary’
    It could refer to either ‘HipSpecifyer.Prelude.genericCoarbitrary’,
                             defined at HipSpecifyer/Prelude.hs:91:1
                          or ‘Test.QuickCheck.genericCoarbitrary’,
                             imported from ‘Test.QuickCheck’ at HipSpecifyer/Prelude.hs:5:1-22
                             (and originally defined in ‘Test.QuickCheck.Arbitrary’)
```

Looks like there's a conflict with QuickCheck. This happens for QuickCheck 2.8 from Hackage and commit 98766f5fbe from https://github.com/nick8325/quickcheck.git

**Comment by Airini** [comment]
Apologies for it.

The branch `induct-schemes-tac` is most up-to-date (and does not have such an issue). It will soon (next week) be merged into the `master` branch.

**Comment by Warbo** [comment]
Thanks, I've switched to commit f81eb6d630 and it's building fine now :)
